# Generated by Django 5.0.3 on 2024-03-18 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='exterior_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=20)),
                ('beneficiary_last_name', models.CharField(max_length=20)),
                ('beneficiary_document_type', models.CharField(max_length=10)),
                ('beneficiary_document_no', models.CharField(max_length=20)),
                ('passport_number', models.CharField(max_length=20)),
                ('passport_expedition_city', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('bank_name', models.CharField(max_length=20)),
                ('account_type', models.CharField(max_length=10)),
                ('swift_code', models.CharField(max_length=10)),
                ('iban_aba_code_type', models.CharField(max_length=10)),
                ('iban_aba_code', models.CharField(max_length=10)),
                ('account_name', models.CharField(max_length=30)),
                ('account_number', models.CharField(max_length=20)),
                ('bank_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('type', models.CharField(max_length=20)),
                ('concept', models.TextField()),
                ('money_type', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('cenco', models.CharField(max_length=20)),
                ('cex_number', models.CharField(max_length=20)),
                ('observations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(max_length=400)),
                ('proveedor', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_solicitud', models.CharField(max_length=400)),
                ('archivos_adjuntos', models.FileField(upload_to='archivos_solicitud/')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('identification', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicate', models.CharField(max_length=20)),
                ('payment_order_code', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('cost_center', models.CharField(max_length=20)),
                ('dependency', models.CharField(max_length=30)),
                ('destiny_city', models.CharField(max_length=30)),
                ('travel_date', models.DateField()),
                ('return_date', models.DateField()),
                ('motive', models.TextField()),
                ('foreign_money', models.BooleanField()),
                ('money', models.CharField(max_length=10)),
                ('last_day_at_icesi', models.DateField()),
                ('elaborator_name', models.CharField(max_length=20)),
                ('orderer_name', models.CharField(max_length=20)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SistemaContableApp.bank_account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SistemaContableApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='expense_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('advance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaContableApp.advance')),
            ],
        ),
        migrations.CreateModel(
            name='audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comments', models.TextField()),
                ('assigned_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaContableApp.following')),
            ],
        ),
        migrations.CreateModel(
            name='Legalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legalization_date', models.DateField()),
                ('cost_center', models.CharField(max_length=30)),
                ('dependency', models.CharField(max_length=30)),
                ('destiny', models.CharField(max_length=20)),
                ('travel_date', models.DateField()),
                ('return_date', models.DateField()),
                ('motive', models.TextField()),
                ('value', models.IntegerField()),
                ('employee_balance', models.IntegerField()),
                ('icesi_balance', models.IntegerField()),
                ('descount_in_one_quote', models.BooleanField()),
                ('elaborator_name', models.CharField(max_length=20)),
                ('orderer_name', models.CharField(max_length=20)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SistemaContableApp.bank_account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SistemaContableApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('support_no', models.IntegerField()),
                ('third_person_name', models.CharField(max_length=30)),
                ('third_person_nit', models.CharField(max_length=20)),
                ('concept', models.TextField()),
                ('money', models.CharField(max_length=10)),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('legalization_facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaContableApp.legalization')),
            ],
        ),
        migrations.AddField(
            model_name='following',
            name='actual_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SistemaContableApp.state'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('decription', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaContableApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicate', models.CharField(max_length=20)),
                ('payment_order_code', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('cenco', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=10, max_digits=20)),
                ('concept', models.TextField()),
                ('description', models.TextField()),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SistemaContableApp.bank_account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SistemaContableApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='following',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SistemaContableApp.user'),
        ),
        migrations.CreateModel(
            name='charge_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.TextField()),
                ('value', models.CharField(max_length=20)),
                ('retention_392_401', models.BooleanField()),
                ('retention_383', models.BooleanField()),
                ('declarant', models.BooleanField()),
                ('colombian_resident', models.BooleanField()),
                ('city', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('cex', models.CharField(max_length=20)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SistemaContableApp.bank_account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SistemaContableApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='bank_account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaContableApp.user'),
        ),
    ]
