# Generated by Django 5.0.3 on 2024-03-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaContableApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='color',
            field=models.CharField(choices=[('rojo', 'Rojo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(choices=[('pendiente de aceptación', 'Pendiente de aceptación'), ('en revisión', 'En revisión'), ('revisado', 'Revisado'), ('aprovado', 'Aprobado'), ('aceptado', 'Aceptado'), ('Rechazado por contabilidad', 'Rechazado por contabilidad')], max_length=30),
        ),
    ]
