# Generated by Django 5.0.3 on 2024-05-04 16:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaContableApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changed', models.DateTimeField(default=django.utils.timezone.now)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaContableApp.following')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SistemaContableApp.state')),
            ],
        ),
        migrations.AddField(
            model_name='following',
            name='state_history',
            field=models.ManyToManyField(related_name='followings', through='SistemaContableApp.StateChange', to='SistemaContableApp.state'),
        ),
        migrations.AddField(
            model_name='state',
            name='state_history',
            field=models.ManyToManyField(related_name='following_state_history', through='SistemaContableApp.StateChange', to='SistemaContableApp.state'),
        ),
    ]
