# Generated by Django 5.0.2 on 2024-03-23 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaContableApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge_account',
            options={},
        ),
    ]
