# Generated by Django 5.0.3 on 2024-03-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaContableApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('identificacion', models.CharField(max_length=200)),
                ('sumadeValorEnLetras', models.CharField(max_length=200)),
                ('sumadeValorEnNumeros', models.CharField(max_length=200)),
                ('concepto', models.CharField(max_length=200)),
                ('ciudadYFecha', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('nombreDelBanco', models.CharField(max_length=200)),
                ('tipoDeCuenta', models.CharField(max_length=200)),
                ('NoDeCuenta', models.CharField(max_length=200)),
                ('cexNo', models.CharField(max_length=200)),
            ],
        ),
    ]
