# Generated by Django 5.0.3 on 2024-04-28 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaContableApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicate', models.CharField(max_length=20)),
                ('payment_order_code', models.CharField(max_length=20)),
                ('request_date', models.DateField()),
                ('traveler_name', models.CharField(max_length=50)),
                ('traveler_id', models.CharField(default='', max_length=10)),
                ('cost_center', models.CharField(max_length=30)),
                ('dependency', models.CharField(max_length=30)),
                ('destiny_city', models.CharField(max_length=20)),
                ('travel_date', models.DateField()),
                ('return_date', models.DateField()),
                ('motive', models.TextField()),
                ('currency_type_of_advance_value', models.CharField(choices=[('PESOS COLOMBIANOS', 'PESOS COLOMBIANOS'), ('DOLARES', 'DOLARES'), ('EUROS', 'EUROS')], max_length=20)),
                ('last_day_in_icesi', models.DateField()),
                ('descount_in_one_quote', models.BooleanField()),
                ('orderer_name', models.CharField(max_length=50)),
                ('elaborator_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('money_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='SistemaContableApp.advancepayment')),
            ],
        ),
    ]
