# Generated by Django 5.0.3 on 2024-03-18 08:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaContableApp', '0002_alter_state_color_alter_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='close_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='color',
            field=models.CharField(choices=[('gray', 'Gris'), ('orange', 'Naranja'), ('yellow', 'Amarillo'), ('green', 'Verde'), ('blue', 'Azul'), ('red', 'Rojo')], max_length=10),
        ),
    ]
