# Generated by Django 5.0.3 on 2024-05-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaContableApp', '0002_statechange_following_state_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statechange',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
