# Generated by Django 5.0.3 on 2024-03-18 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaContableApp', '0003_following_close_date_alter_state_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='actual_state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='following',
            name='color',
            field=models.CharField(choices=[('gray', 'Gris'), ('orange', 'Naranja'), ('yellow', 'Amarillo'), ('green', 'Verde'), ('blue', 'Azul'), ('red', 'Rojo')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='following',
            name='state',
            field=models.CharField(choices=[('pendiente de aceptación', 'Pendiente de aceptación'), ('en revisión', 'En revisión'), ('revisado', 'Revisado'), ('aprovado', 'Aprobado'), ('aceptado', 'Aceptado'), ('Rechazado por contabilidad', 'Rechazado por contabilidad')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='type',
            field=models.CharField(choices=[('saving', 'De ahorros'), ('current', 'Corriente')], max_length=10),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
